apiVersion: v1
stringData:
  app_passwd: {{ .Values.applications.password }} #New application password
  default_app_passwd: {{ .Values.applications.defaultPassword  }}  #Default password
  email_passwd: {{.Values.externalMailServer.password }}
  email_user: {{.Values.externalMailServer.username }} #Email User
kind: Secret
metadata:
  name: {{ $.Release.Name }}-app-secrets
type: Opaque